# Generated by Django 3.2.8 on 2021-10-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entrt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrt',
            new_name='Entry',
        ),
    ]
